apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_DB: "db-data"
  POSTGRES_USER: "db-user"
  POSTGRES_PASSWORD: "db-password"
  PGDATA: "/dbdata"
  pg_service.conf: |
    [postgres_svc]
    host=postgres-primary
    port=5432
    dbname=db-data
    user=db-user
    password=db-password
    sslmode=disable

